version: "3"
services:
  mysqldb:
     container_name: mysqldb
     image: "mysql:8.0"
     restart: always
     ports:
      - 3306:3306
     environment:
        MYSQL_DATABASE: pancakes
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker

  app:
    image: pancakes_unlimited_docker
    container_name: pancakes
    build: .
    restart: always
    ports: 
        - 8080-8080
    depends_on:
        - mysqldb